# Generated by Django 3.2.4 on 2021-07-01 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.timestampedmodel')),
                ('title', models.CharField(max_length=50)),
                ('isopen', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=10)),
                ('likenum', models.IntegerField()),
            ],
            bases=('core.timestampedmodel',),
        ),
        migrations.CreateModel(
            name='WebMark',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.timestampedmodel')),
                ('title', models.CharField(max_length=50)),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test.repository')),
            ],
            bases=('core.timestampedmodel',),
        ),
        migrations.DeleteModel(
            name='Content',
        ),
    ]
