# Generated by Django 3.2.4 on 2021-07-01 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('test', '0002_auto_20210701_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webmark',
            name='repo',
        ),
        migrations.AddField(
            model_name='repository',
            name='for_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_repository', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='webmark',
            name='for_repository',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_webmark', to='test.repository'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='isopen',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='yes', max_length=10),
        ),
        migrations.AlterField(
            model_name='repository',
            name='likenum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='repository',
            name='title',
            field=models.CharField(default='Repository title', max_length=50),
        ),
        migrations.AlterField(
            model_name='webmark',
            name='title',
            field=models.CharField(default='WebMark name', max_length=50),
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.timestampedmodel')),
                ('urladdress', models.CharField(default='', max_length=300)),
                ('description1', models.CharField(default='', max_length=10)),
                ('description2', models.CharField(default='', max_length=10)),
                ('description3', models.CharField(default='', max_length=10)),
                ('for_webmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_url', to='test.webmark')),
            ],
            bases=('core.timestampedmodel',),
        ),
    ]
