# Generated by Django 3.2.4 on 2021-07-01 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0003_auto_20210701_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webmark',
            name='for_repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_webmark', to='test.repository'),
        ),
    ]
