# Generated by Django 3.2.4 on 2021-07-01 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0004_alter_webmark_for_repository'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webmark',
            name='for_repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webmark', to='test.repository'),
        ),
    ]
