# Generated by Django 3.2.4 on 2021-07-02 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0006_auto_20210701_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='urlname',
            field=models.CharField(default='', max_length=100),
        ),
    ]
