# Generated by Django 3.2.4 on 2021-07-02 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0007_url_urlname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='urlname',
        ),
    ]
