# Generated by Django 3.2.4 on 2021-07-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0008_remove_url_urlname'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='urltitle',
            field=models.CharField(default='', max_length=100),
        ),
    ]
