# Generated by Django 3.2.4 on 2021-08-08 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0010_auto_20210704_1910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='description1',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='url',
            name='description2',
        ),
        migrations.RemoveField(
            model_name='url',
            name='description3',
        ),
    ]
