# Generated by Django 3.2.4 on 2021-08-11 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0012_alter_url_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='title',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='description',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='urladdress',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='urltitle',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='webmark',
            name='title',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
