# Generated by Django 3.2.4 on 2021-08-11 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0013_auto_20210811_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='description',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
    ]
